# Generated by Django 5.2.8 on 2025-11-27 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nama Paket')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Harga (Rp)')),
                ('duration_days', models.IntegerField(verbose_name='Durasi (Hari)')),
                ('max_devices', models.IntegerField(default=1, verbose_name='Batas Perangkat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Tersedia')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Jumlah Pembayaran')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Transaksi')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('SUCCESS', 'Berhasil'), ('FAILED', 'Gagal')], default='PENDING', max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Mulai')),
                ('end_date', models.DateTimeField(verbose_name='Tanggal Berakhir')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.subscriptionplan', verbose_name='Paket Langganan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
        ),
    ]
