# Generated by Django 5.2.8 on 2025-12-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maksimal harga hingga Rp 999.999,99.', max_digits=7),
        ),
    ]
