# Generated by Django 5.2.8 on 2025-12-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_subscriptionplan_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Berhasil'), ('PENDING', 'Menunggu Pembayaran'), ('FAILED', 'Gagal')], default='SUCCESS', max_length=10),
        ),
    ]
